[package]
name = "r6s_cheat"
version = "1.0.0"
edition = "2021"

[dependencies]
gtk = "0.9.0"
gdk = "0.9.0"
rand = "0.8.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[lib]
crate-type = ["cdylib"]